add error message when swap price is too high
OriginProtocol/origin-dollar pull request #1049
Opened 2022-07-22 16:21 UTC by rolandpo

This adds a `Price too high` error message when the `Est. received` amount differs from the input amount by more than 10%, which prevents clearly unfavourable prices and large percentages in red from cluttering the screen. It's applicable to all routes other than Flipper and Vault

issue #1047

2022-07-22 16:40 UTC, micahalcorn requested changes

2022-07-22 16:40 UTC, micahalcorn commented on dapp/src/components/buySell/ContractsTable.js
> +    price_too_high: fbt('Price too high', 'Swap estimations: price too high'),
Should we remove `slippage_too_high` and just talk about price in those cases?

2022-07-22 17:15 UTC, rolandpo commented
replaced `slippage_too_high` with `price_too_high`

2022-07-22 19:46 UTC, micahalcorn approved these changes

2022-07-22 19:46 UTC, merged

2022-08-03 14:23 UTC, sparrowDom reviewed
Left a few comments great work!

2022-08-03 14:23 UTC, sparrowDom commented on dapp/src/hooks/useSwapEstimator.js
> +      console.log()
this can probably be removed

2022-08-03 14:23 UTC, sparrowDom commented on dapp/src/hooks/useSwapEstimator.js
> +      const decimals = swapMode === 'redeem' || selectedCoin === 'dai' ? 18 : 6
almost same bit of code happens 3 times. Looks like it could be refactored into a function and called 3 times