Increase performance fee and update Buyback for increased Treasury
OriginProtocol/origin-dollar pull request #1277
Opened 2023-04-03 16:05 UTC by shahthepro

- [x] Increase performance fee to 20%
- [x] Add support for transferring a part of the fee to the strategist
- [x] Add deployment script for the new contract
- [x] Move funds out of the old Buyback contract
---------
If you made a contract change, make sure to complete the checklist below before merging it in master.

Refer to our [documentation](https://github.com/OriginProtocol/security) for more details about contract security best practices.

Contract change checklist:
  - [ ] Code reviewed by 2 reviewers. 
  - [ ] Copy & paste code review [security checklist](https://github.com/OriginProtocol/security/blob/master/templates/Contract-Code-Review-Example.md) below this checklist.
  - [x] Unit tests pass
  - [x] Slither tests pass with no warning
  - [x] Echidna tests pass if PR includes changes to OUSD contract (not automated, run manually on local)

2023-04-06 16:41 UTC, DanielVF requested changes
# Buyback Review


#### Requirements

Rather than spending all protocol fees on buying back OGV, we can take a 0-100% percentage and directly send it to a treasury account. 

This PR will also configure the vault to increase the percentage sent to the buyback from 10% to 20%

#### Deployment Considerations

- [ ] We need to check and update our current monitoring. 
- [ ] We'll need to update the expected limits in our current automation around buybacks. It should error at the moment, since the amount received is 50% less.
- [ ] (🟠 Change needed) I don't think there's any OGN on the "old" buyback contract - I think it's on an even older one. We should probably actually move that very old OGN to the strategist address. 
- [ ] We'll need to not do buybacks using the old contract once we deploy this contract.

#### Internal State

_All state is config_

#### Attack

If attacked, this contract has a limited amount of damage that can be done, since it only holds funds in flight.

We assume the min OGV received amount is set honestly, since low numbers there could provide MEV opportunity.

The funds recipients are all loaded from config variables. If they could be changed, that would be an attack. It looks like all config set methods have the correct authentication on them.

#### Logic

The math involves splitting up the funds between swapping and transferring. This looks correct.


#### Tests

  - [x] Each publicly callable method has a test
  - [ ] Each logical branch has a test
  - [ ] Each require() has a test
  - [ ] Edge conditions are tested

#### Flavor

- [ ] (🟠 Change optional) We could deduplicate the uniswap sets by making them into a private method like we do with the other config methods.

#### Overflow

_No problems_

#### Proxy

_No proxy_

#### Black magic

_No black magic._

#### Dependencies

_No dependency changes_

#### Deploy

- [x] Check that any deployer permissions are removed after deploy

#### Authentication

- [x] Never use tx.origin
- [x] Check that every external/public function should actually be external
- [x] Check that every external/public function has the correct authentication

#### Cryptographic code

_No Crypto_

#### Gas problems

_No loops_

#### External calls

- [x] No slippage attacks (we need to validate expected tokens received)
- [x] Oracles, one of:
  - [x] No oracles
  - [ ] Oracles can't be bent
  - [ ] If oracle can be bent, it won't hurt us.
- [x] Don't call balanceOf for external contracts to determine what they will do, when they instead use internal accounting?


#### Ethereum

- [x] Contract does not send or receive Ethereum.
- [x] Contract has no payable methods.

2023-04-07 05:39 UTC, shahthepro commented
@DanielVF Regarding the OGN, [this is the Buyback contract](https://etherscan.io/address/0x77314eb392b2be47c014cde0706908b3307ad6a9) that has about 938k OGN balance. 

The deployment and script files use that address for OGN as well. If you run the deployment on fork and run the script, it'll print the balances it has. Sorry if my naming convention was confusing but I used `oldBuybackContract` for the the one holding OGN and `recentBuybackContract` for the currently active one 😅

2023-04-17 14:03 UTC, DanielVF commented on contracts/deploy/052_upgrade_buyback.js
> +          // 7. Transfer OGN balance from Governor to New Contract
Since the community has voted on spending the OGN, let's have the old OGN end up on the strategist multisig, rather than the new buyback.

2023-04-17 14:18 UTC, DanielVF approved these changes

2023-04-17 17:05 UTC, merged