ARM Buyback
OriginProtocol/origin-dollar pull request #2240
Opened 2024-09-17 15:15 UTC by clement-ux

# Create a new buyback for ARM

Create a new buyback for ARM, using `WETH` as `oToken`. This use the same contract as `OETHBuyback.sol` and `OUSDBuyback.sol`.

## Code Change Checklist

To be completed before internal review begins:

- [ ]  The contract code is complete
- [ ]  Executable deployment file
- [ ]  Fork tests that test after the deployment file runs
- [ ]  Unit tests *if needed
- [ ]  The owner has done a [full checklist review](https://github.com/OriginProtocol/security/blob/master/templates/Contract-Code-Review.md) of the code + tests

Internal review:

- [ ] Two approvals by internal reviewers

## Deploy checklist

Two reviewers complete the following checklist:

```
- [ ] All deployed contracts are listed in the deploy PR's description
- [ ] Deployed contract's verified code (and all dependencies) match the code in master
- [ ] The transactions that interacted with the newly deployed contract match the deploy script.
- [ ] Governance proposal matches the deploy script
- [ ] Smoke tests pass after fork test execution of the governance proposal
```

2024-09-18 18:38 UTC, DanielVF commented on contracts/deploy/mainnet/107_arm_buyback.js.js
> +        "0xF14BBdf064E3F67f51cd9BD646aE3716aD938FDC", // MS 2
Let's look these up from `addresses.mainnet`, instead of having them separately coded here.

2024-09-18 18:58 UTC, DanielVF submitted a review, later dismissed

2024-09-18 19:02 UTC, DanielVF commented
@clement-ux Can you make the linter happy? Thanks.

2024-09-18 19:07 UTC, clement-ux commented
> @clement-ux Can you make the linter happy? Thanks.

I was sure I'd done it before push. Sorry, fixed now.

2024-09-19 05:09 UTC, naddison36 requested changes
Looks good. My only change would be getting the strategist address

2024-09-19 05:09 UTC, naddison36 commented on contracts/deploy/mainnet/107_arm_buyback.js.js
> +        addresses.mainnet.MultiSig2OutOf9, // MS 2
you can get the strategist address with
```js
const { strategistAddr } = await getNamedAccounts();
```

This is configured in the Hardhat config

2024-09-19 13:27 UTC, naddison36 approved these changes

2024-09-20 18:42 UTC, merged